package by.tc.opinionpull.controller.command;

public enum CommandName {
    LOGIN, SIGNIN, CHANGE_LANGUAGE, LOGOUT, LOAD_CONTENT, PASS_POLL, COMPLETE_POLL, USER_SETTINGS, EDIT, DELETE_POLL, EDIT_POLL, EDIT_QUESTION, EDIT_ANSWER, DELETE_QUESTION, DELETE_ANSWER,

    WRONG_REQUEST;
}
